// Whitworth Art Gallery (University of Manchester) — wild silk records
// Verbatim from whitworthcollections.manchester.ac.uk

const whItems = [
  {
    id: 1,
    objectID: "T.1985.105",
    accession: "T.1985.105",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/tussur-shared.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/e3b3d67d-04b0-3f3a-8e17-d1d95e9fc0c8/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk with narrow borders of small boteh woven in purple silk. One loom end is preserved with a band of bare warp ends flanked by pairs of bands of purple silk, the other end is cut. The cloth includes some dark, streaky patches of yarn near the selvedges.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 2,
    objectID: "T.1985.106",
    accession: "T.1985.106",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/tussur-shared.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/9a19976c-05bd-3058-8119-50fbbc383fb4/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk with narrow borders of small boteh woven in purple silk. One loom end preserved with a band of bare warp ends flanked by a series of bands of purple silk.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 3,
    objectID: "T.1985.107",
    accession: "T.1985.107",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/tussur-shared.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/c6f9816f-00c0-3999-8c77-660ee3c47ae8/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk with narrow borders of small boteh woven in purple silk. One loom end preserved with a band of bare warp ends flanked by pairs of bands of purple silk, the other end is cut. The cloth includes some dark, streaky patches of yarn near the selvedges. There is some water staining at one end.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 4,
    objectID: "T.1985.109",
    accession: "T.1985.109",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/tussur-shared.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/120e4fec-6e45-34a8-9335-83ea3d358b2c/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 5,
    objectID: "T.1985.110",
    accession: "T.1985.110",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/T-1985-110.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/71779912-f4b0-3014-95f2-a21f89311957/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk with narrow borders of small boteh woven in purple silk edged with purple pin stripes on both sides. Both loom ends are preserved, each with a band of bare warp ends flanked by a series of bands of purple silk.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 6,
    objectID: "T.1985.129",
    accession: "T.1985.129",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/T-1985-129.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/19b6887b-38eb-3a16-9734-9198f6451e5f/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk with narrow borders of small boteh woven in purple silk. One loom end preserved with a band of bare warp ends flanked by pairs of bands of purple silk, the other end is cut. The cloth includes some dark, streaky patches of yarn near the selvedges. There is an L-shaped tear in the cloth.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 7,
    objectID: "T.9682",
    accession: "T.9682",
    title: "Length of wild silk",
    objectName: "cloth",
    imageFile: "wh/T-9682.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/c17ba9aa-7322-3236-8c55-8720aeef26dc/",
    culture: "Indian, maker",
    country: "India / Nepal",
    region: "Nepal",
    objectDate: "1880-1884",
    medium: "Length of wild silk woven from Z-spun yarn dyed before weaving. There is a band of three picks of undyed yarn 20mm from the loom end. (Stitches indicate where a label was formerly attached to one corner).",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Wild silk (other)"
  },
  {
    id: 8,
    objectID: "T.2018.12",
    accession: "T.2018.12",
    title: "Sari",
    objectName: "sari",
    imageFile: "wh/T-2018-12.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/7927ea03-c081-3bcc-a004-62cbb953a01e/",
    culture: "",
    country: "India",
    region: "Bengal",
    objectDate: "",
    medium: "Sari, hand woven with tussah silk and black silk jamadani. Measurements include sari choli (blouse) allowance. This means extra fabric was woven at the time of making so that it could be cut off from the sari and tailor-made to create a matching choli or blouse for the wearer/owner.",
    classification: "textiles (woven)",
    department: "",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tussore / Tussah"
  },
  {
    id: 9,
    objectID: "T.2018.11",
    accession: "T.2018.11",
    title: "Sari",
    objectName: "sari",
    imageFile: "wh/T-2018-11.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/58e797dc-a248-3586-bf08-33e6991a3cf3/",
    culture: "",
    country: "India",
    region: "Bengal",
    objectDate: "2016",
    medium: "This is a unique handwoven sari in tussah silk with black silk. Tussah silk is a highly coveted type of silk found in the North Eastern part of India and is produced by wild silk moths instead of the cultivated moths used for the white, smooth silks. Tussah silk moths feed on a wide range of vegetation giving an unexpected variety of natural colours, including cream, stone, honey and a deeper biscuit-brown colour. The characteristic honey colour is often produced where the moth feeds on oak leaves. Jamdani is an ancient art of weaving very fine quality muslin fabric that combines intricate floral or geometric designs with the application of a localised extra weft as the fabric is woven (the weft is the yarn which runs horizontally, across the cloth). It is widely known as the rarest and most sophisticated example of handloom weaving and today is mainly produced in the states of Bengal and Uttar Pradesh, India and the city of Dhaka, Bangladesh. This sari was purchased from Indian Story in Goa, India who specialise in commissioning unique handwoven garments after months of careful research, travel and dialogue with highly sought-after weavers.",
    classification: "textiles (woven)",
    department: "",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tussore / Tussah"
  }
];
