/* ============================================================
   Art Institute of Chicago — wild silk objects from Asia (16)
   Source: Art Institute of Chicago Open Access API (api.artic.edu).
   Every field below is VERBATIM from the source record.
   Images are loaded directly from ARTIC's IIIF endpoint.
   ============================================================ */

const articItems = [
  {
    id: 1,
    objectID: 36599,
    title: "Woman's Waitao (Semiformal Domestic Surcoat)",
    artistDisplay: "Han-Chinese\nChina",
    dateDisplay: "Qing dynasty (1644–1911), 1875/1900",
    placeOfOrigin: "China",
    medium: "Silk, warp-float faced 7:1 satin weave; embroidered with gold-leaf-over-lacquered-paper-strip-wrapped wild silk and silk, laid work and couching; collar tape, closures, and lining: silk, warp-float faced 7:1 satin weave; metal button",
    dimensions: "100.3 × 155.8 cm (39 1/2 × 61 3/8 in.)",
    creditLine: "Gift of Eleanor Burton",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic1.jpg",
    sourceUrl: "https://www.artic.edu/artworks/36599",
    fibreBucket: "Wild silk"
  },
  {
    id: 2,
    objectID: 47257,
    title: "Woman's Ao (Short Robe)",
    artistDisplay: "Han-Chinese\nChina",
    dateDisplay: "Qing dynasty (1644–1911), 1870/90",
    placeOfOrigin: "China",
    medium: "Silk, 7:1 satin damask weave; embroidered with silk and gold-leaf-over-lacquered-paper-strip-wrapped silk in knot, satin, and stem stitches; laid work and couching; sleeve bands: silk, warp-float faced 7:1 satin weave; embroidered with silk, gold-leaf-over-lacquered-paper-strip-wrapped wild silk, and gilt-metal-strip-wrapped silk in eyelet, feather, knot, satin, single satin, and stem stitches; laid work and couching; ribbons: silk and gold-leaf-over-lacquered-paper-strip-wrapped silk, complementary warp 7:1 satin weave with plain interlacings of secondary binding warps and self-patterning ground wefts; trim and closures: silk, warp-float faced 7:1 and 4:1 satin weaves; lined with silk, plain weave",
    dimensions: "109.5 × 145.1 cm (43 1/8 × 57 1/8 in.); Repeat: 10.8 × 9.2 cm (4 1/4 × 3 5/8 in.)",
    creditLine: "Gift of Mrs. John J. Abbott",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic2.jpg",
    sourceUrl: "https://www.artic.edu/artworks/47257",
    fibreBucket: "Wild silk"
  },
  {
    id: 3,
    objectID: 87374,
    title: "Obi (Belt)",
    artistDisplay: "Japan",
    dateDisplay: "Meiji period (1868–1912), 1875/1900",
    placeOfOrigin: "Japan",
    medium: "Silk, cotton, wild silk and gold-leaf-over-lacquered-paper strips, warp-float faced 2:1 'S' twill weave with supplementary patterning and brocading wefts bound in twill interlacings",
    dimensions: "179.1 × 65.1 cm (70 1/2 × 25 5/8 in.); Warp repeat: H.: 104.2 cm (41 in.)",
    creditLine: "Gift of the Orientals",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic3.jpg",
    sourceUrl: "https://www.artic.edu/artworks/87374",
    fibreBucket: "Wild silk"
  },
  {
    id: 4,
    objectID: 150734,
    title: "Hanging",
    artistDisplay: "Japan",
    dateDisplay: "late Edo period (1789–1868)/Meiji period (1868–1912), 1825/1900",
    placeOfOrigin: "Japan",
    medium: "Cotton, plain weave; covered with paper; embroidered with silk, cotton and wild silk, in bullion, satin, single satin, and stem stitches; Chinese knot, laid work and couching; edged with silk and gold-leaf-over-lacquered-paper strip, warp-float faced 4:1 'z' twill interlacings of secondary binding warps and supplementary patterning wefts",
    dimensions: "239.8 × 219.5 cm (94 1/2 × 86 3/8 in.)",
    creditLine: "Gift of Gaylord Donnelley in memory of Frances Gaylord Smith",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic4.jpg",
    sourceUrl: "https://www.artic.edu/artworks/150734",
    fibreBucket: "Wild silk"
  },
  {
    id: 5,
    objectID: 153710,
    title: "Hitoe",
    artistDisplay: "Japan",
    dateDisplay: "Meiji period (1868–1912)/Taishô period (1912–1926), c. 1900/16",
    placeOfOrigin: "Japan",
    medium: "Silk and wild silk, plain weave; resist dyed (kasuri); collar lining of silk and rayon, plain weave self-patterned by rows of gauze crossings (yoko-ro)",
    dimensions: "161.8 × 133.5 cm (63 5/8 × 52 1/2 in.)\nRepeat: 13.6 × 12.7 cm (5 3/8 × 5 in.)\nShoulder to hem length: 151.2 cm (59 1/2 in.)\nsleeve length: 37.7 cm (14 3/4 in.)\ncollar back to hem length: 85.7 cm (33 3/4 in.)\nwidth at hem: 61.2 cm (24 in.)\nwidth of sleeve panel: 33.8 cm (13 1/4 in.)\nwidth of center front panel hem overlap: 15.2 cm (6 in.)\nwidth of collar band: 11.3 cm (4 1/2 in.)",
    creditLine: "Gift of Mary V. and Ralph E. Hays",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic5.jpg",
    sourceUrl: "https://www.artic.edu/artworks/153710",
    fibreBucket: "Wild silk"
  },
  {
    id: 6,
    objectID: 153723,
    title: "Juban",
    artistDisplay: "Japan",
    dateDisplay: "Shôwa period (1926–1989), 1940/45\n(fabric dates prior to this date)",
    placeOfOrigin: "Japan",
    medium: "Silk, plain weave; stenciled (yûzenzome: kata utsushi) sleeve in rayon and silk, plain weave; stenciled (yûzenzome: kata utsushi, itome); collar and collar facing: silk and waste silk, plain weave; stenciled (yûzenzome: utsushi); body lining: silk, plain weave (heiken); sleeve lining: silk and wild silk, plain weave with supplementary patterning; resist dyed and stenciled (yûzenzome: utsushinori)",
    dimensions: "96.8 × 127.3 cm (38 1/8 × 50 1/8 in.)\nRepeat (body fabric): 35.5 × 24.7 cm (14 × 9 3/4 in.)\nShoulder to hem length: 91.3 cm (35 7/8 in.)\nSleeve length: 49.5 cm (19 1/2 in.)\nCollar back to hem length: 59 cm (23 1/4 in.) \nWidth at hem: 61.5 cm (24 1/4 in.)\nWidth of sleeve panel: 32.2 cm (12 5/8 in.)\nWidth of center front panel hem overlap: 6.8 cm (2 5/8 in.)\nWidth of collar band: 19.3 cm (7 5/8 in.)",
    creditLine: "Gift of Mary V. and Ralph E. Hays",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic6.jpg",
    sourceUrl: "https://www.artic.edu/artworks/153723",
    fibreBucket: "Wild silk"
  },
  {
    id: 7,
    objectID: 153774,
    title: "Katagawa Obi (Side Patterned Belt)",
    artistDisplay: "Japan",
    dateDisplay: "Taishô period (1912–1926), c. 1914",
    placeOfOrigin: "Japan",
    medium: "a: Silk and gold-leaf-over-lacquered-paper strip, warp-dyed (kasuri) plain weave with creped wefts and with supplementary brocading wefts (chirimen nuitori) bound by main warp in weft float faced 1:5 'S'twill interlacings\nb: Silk, wild silk and gold-leaf-over-lacquered-paper-strip wrapped silk, warp-stripe plain weave with paired wefts and strips of 3:1 interlacing in alternation with supplementary brocading wefts bound by main warps in plain interlacings",
    dimensions: "a: 366.7 × 40.3 cm (144 3/8 × 15 7/8 in.); Warp repeat: H.: 39.3 cm (15 1/2 in.); b: 360.2 × 33 cm (141 3/4 × 13 in.)",
    creditLine: "Gift of Mary V. and Ralph E. Hays",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic7.jpg",
    sourceUrl: "https://www.artic.edu/artworks/153774",
    fibreBucket: "Wild silk"
  },
  {
    id: 8,
    objectID: 157429,
    title: "Woman's Surcoat",
    artistDisplay: "Han-Chinese\nChina",
    dateDisplay: "Qing dynasty (1644–1911), 1860/90",
    placeOfOrigin: "China",
    medium: "Body: silk, warp-float faced 7:1 satin weave; embroidered with silk and gold-leaf-over-lacquered-paper-strip-wrapped wild silk in laid work and couching; neck, front, hem, sides and sleeves: silk, warp-float faced 7:1 satin weave; embroidered with silk and gold-leaf-over-lacquered-paper-strip-wrapped silk wrapped cotton in knot, satin and stem stitches; laid work and couching; edged with silk, warp-float faced 7:1 satin weave; sleeve bands: silk, warp-float faced 7:1 satin weave; embroidered with silk and gold-leaf-over-lacquered-paper-strip-wrapped silk in knot, satin and stem stitches; laid work and couching; three ribbons: silk and gold-leaf-over-lacquered-paper-strip-wrapped cotton, plain weave self-patterned by main warp floats (narrowest has gold-leaf-over-lacquered-strip-wrapped silk); lined with silk, plain weave",
    dimensions: "97.5 × 130.2 cm (38 3/8 × 51 1/4 in.)",
    creditLine: "The Art Institute of Chicago, Department of Textiles Collection",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic8.jpg",
    sourceUrl: "https://www.artic.edu/artworks/157429",
    fibreBucket: "Wild silk"
  },
  {
    id: 9,
    objectID: 157685,
    title: "Fukusa (Gift Cover)",
    artistDisplay: "Japan",
    dateDisplay: "1912/26, Taishô period (1912–1926)",
    placeOfOrigin: "Japan",
    medium: "Woven in one piece (hikikaeshi); Mon side: silk, plain weave (shioze); dye extracted through stenciled chemical dye stripper (bassen); Patterned side: silk, plain weave (shioze); resist dyed and stenciled (yûzenzome: suri yûzenzome); embroidered with silk and wild silk in straight stitches: interlined with cotton, plain weave; silk, running \"controlling\" stitches along all edges; corner: silk and gold-leaf-over-lacquered-paper-strip wrapped cotton, oblique interlacing over wrapped cotton ball, knotted and re-plied fringe tassels",
    dimensions: "76 × 66.6 cm (39 7/8 × 26 1/4 in.)",
    creditLine: "Gift of Mary V. and Ralph E. Hays",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic9.jpg",
    sourceUrl: "https://www.artic.edu/artworks/157685",
    fibreBucket: "Wild silk"
  },
  {
    id: 10,
    objectID: 157690,
    title: "Fukusa (Gift Cover)",
    artistDisplay: "Japan",
    dateDisplay: "1926/29, early Shôwa period (1926–1989)",
    placeOfOrigin: "Japan",
    medium: "Woven in one piece (hikikaeshi); Mon side: silk, warp resist dyed plain weave; Patterned side: silk, wild silk, rayon, cotton and gold- and silver-leaf-on-lacquered-paper-strip wrapped cotton, plain weave with supplementary patterning and brocading wefts bound by main warps in weft-float faced 1:3 \"s\" twill and plain interlacings mounted to paper; inscribed with ink; attached tying tapes of cotton, 2:2 oblique twill interlacing; both selvages present",
    dimensions: "72.8 × 68.5 cm (28 5/8 × 27 in.)",
    creditLine: "Gift of Mary V. and Ralph E. Hays",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic10.jpg",
    sourceUrl: "https://www.artic.edu/artworks/157690",
    fibreBucket: "Wild silk"
  },
  {
    id: 11,
    objectID: 157715,
    title: "Furoshiki (Wrapping Cloth)",
    artistDisplay: "Japan",
    dateDisplay: "early Shôwa period (1926–1989), 1926/35",
    placeOfOrigin: "Japan",
    medium: "Wild silk, plain weave; stenciled (yûzenzome: utsushinori yûzenzome)",
    dimensions: "84.9 × 85.2 cm (33 1/2 × 33 1/2 in.)",
    creditLine: "Gift of Mary V. and Ralph E. Hays",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic11.jpg",
    sourceUrl: "https://www.artic.edu/artworks/157715",
    fibreBucket: "Wild silk"
  },
  {
    id: 12,
    objectID: 183142,
    title: "Kesa",
    artistDisplay: "Japan",
    dateDisplay: "Early 20th century, Meiji period (1868–1912)/ Taishô period (1912–1926)",
    placeOfOrigin: "Japan",
    medium: "Silk, wild silk, and gilt-paper strip; twill weave with secondary binding warps and supplementary patterning wefts",
    dimensions: "115.6 × 186.2 cm (45 1/2 × 73 1/4 in.)",
    creditLine: "Gift of Ralph E. Hays in memory of Mary Van Artsdalen Hays",
    department: "Textiles",
    classification: "textile",
    description: "<p>The pattern of this woven kesa reflects the strong influence of European styles on Japanese designers during the first quarter of the 20th century. The pattern is dominated by highly ornamentalized butterflies and complex floral forms, combined with a whirring energy reminiscent of 1920s Art Deco.</p>\n",
    imageUrl: "images/artic/artic12.jpg",
    sourceUrl: "https://www.artic.edu/artworks/183142",
    fibreBucket: "Wild silk"
  },
  {
    id: 13,
    objectID: 183144,
    title: "Kesa",
    artistDisplay: "Japan",
    dateDisplay: "Meiji period (1868–1912), 1868/1900",
    placeOfOrigin: "Japan",
    medium: "Hiri, yô, jô: silk and gold-leaf-over-lacquered-paper strip, warp-float faced 2:1 'Z' twill weave with weft-float faced 1:2 'Z' twill interlacings of secondary binding warps and supplementary patterning wefts;\nshiten: silk and wild silk, warp-float faced 4:1 satin weave with plain interlacings of secondary binding warps and supplementary patterning wefts",
    dimensions: "112.4 × 184.1 cm (44 1/4 × 72 1/2 in.)",
    creditLine: "Gift of Ralph E. Hays in memory of Mary Van Artsdalen Hays",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic13.jpg",
    sourceUrl: "https://www.artic.edu/artworks/183144",
    fibreBucket: "Wild silk"
  },
  {
    id: 14,
    objectID: 183208,
    title: "Uchishiki (Altar Cloth)",
    artistDisplay: "Japan",
    dateDisplay: "1900/20, Meiji period (1868–1912)/Taishô period (1912–1926)",
    placeOfOrigin: "Japan",
    medium: "Silk, cotton, and wild silk, warp-float faced 2:1 'S' twill weave with plain interlacings of secondary binding warps and supplementary patterning wefts; embroidered with silk and gold-leaf-over-lacquered-paper strip-wrapped cotton, paper-padded laidwork and couching",
    dimensions: "132.8 × 130.9 cm (52 1/4 × 51 1/2 in.); Weft repeat: H.: 34 cm (13 3/8 in.)",
    creditLine: "Gift of Ralph E. Hays in memory of Mary Van Artsdalen Hays",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic14.jpg",
    sourceUrl: "https://www.artic.edu/artworks/183208",
    fibreBucket: "Wild silk"
  },
  {
    id: 15,
    objectID: 183419,
    title: "Panel",
    artistDisplay: "Japan",
    dateDisplay: "1894, Meiji period (1868–1912)",
    placeOfOrigin: "Japan",
    medium: "Silk, satin weave; underlaid with pieced cotton, plain weaves; some printed; covered with paper; embroidered with wild silk and silk, silk-wrapped cotton, gold-leaf-over-lacquered-paper strip and gold-leaf-over-lacquered-paper-strip-wrapped cotton and silk in single satin, satin, stem, and  paper padded satin and stem stitches; laid work, couching and padded couching; painted details",
    dimensions: "206.3 × 132.7 cm (81 1/4 × 52 1/4 in.)",
    creditLine: "Gift of the James D. Tigerman Estate",
    department: "Textiles",
    classification: "textile",
    description: "",
    imageUrl: "images/artic/artic15.jpg",
    sourceUrl: "https://www.artic.edu/artworks/183419",
    fibreBucket: "Wild silk"
  },
  {
    id: 16,
    objectID: 190865,
    title: "Cover",
    artistDisplay: "Made in Bengal, India, for the Portuguese market",
    dateDisplay: "1601/50",
    placeOfOrigin: "India",
    medium: "Three panels joined: silk (tussar), plain weave; embroidered with cotton in chain (tambour work) stitches; lining: cotton, plain weave; edging: silk, plain weave with looped and plied warp fringe; attached silk and cotton tassels at all four corners",
    dimensions: "301 × 237.5 cm (118 1/2 × 93 in.)",
    creditLine: "Christa C. Mayer Thurman Textile Endowment",
    department: "Textiles",
    classification: "needlework (visual works)",
    description: "",
    imageUrl: "images/artic/artic16.jpg",
    sourceUrl: "https://www.artic.edu/artworks/190865",
    fibreBucket: "Tussar"
  }
];

const articFilterDefinitions = {
  fibreBucket: ["Tussar", "Wild silk"],
  placeOfOrigin: ["India", "China", "Japan"],
  classification: ["textile", "needlework (visual works)"]
};
