/* ============================================================
   The British Museum — wild silk objects (30 hits)
   Source: britishmuseum.org collection online catalogue.
   Every field below is VERBATIM from the source record.
   Do not paraphrase, normalise, or expand abbreviations.
   ============================================================ */

const bmItems = [
  {
    id: 1,
    objectID: "2000,1213,0.1",
    accession: "2000,1213,0.1",
    title: "Counterpane",
    objectName: "counterpane",
    imageFile: "bm/2000-1213-0-1.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/A_2000-1213-0-1",
    culture: "",
    country: "India",
    region: "Bengal (historic): Satgaon (historic) (probably)",
    objectDate: "17thC(early)",
    medium: "cotton; silk",
    classification: "",
    department: "Asia",
    creditLine: "Purchased from: Dr Henry Ginsburg",
    dimensions: "Length: 272 centimetres; Width: 236",
    fibreBucket: "Tasar"
  },
  {
    id: 2,
    objectID: "1989,0204,0.70",
    accession: "1989,0204,0.70",
    title: "Painting",
    objectName: "painting",
    imageFile: "bm/1989-0204-0-70.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/A_1989-0204-0-70",
    culture: "",
    country: "India",
    region: "Orissa: Bhubaneswar",
    objectDate: "1980-1988",
    medium: "silk",
    classification: "",
    department: "Asia",
    creditLine: "Purchased from: Martand Singh",
    dimensions: "Height: 236 centimetres; Width: 118 centimetres",
    fibreBucket: "Tasar"
  },
  {
    id: 3,
    objectID: "As1992,05.24",
    accession: "As1992,05.24",
    title: "Textile",
    objectName: "textile",
    imageFile: "bm/As1992-05-24.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/A_As1992-05-24",
    culture: "",
    country: "India",
    region: "Bengal (historic) (Dhaka?)",
    objectDate: "20thC(early)",
    medium: "cotton; silk",
    classification: "",
    department: "Asia",
    creditLine: "Purchased from: John Gillow",
    dimensions: "Length: 117 centimetres; Width: 121 centimetres",
    fibreBucket: "Tasar"
  },
  {
    id: 4,
    objectID: "1989,0204,0.71",
    accession: "1989,0204,0.71",
    title: "Painting",
    objectName: "painting",
    imageFile: "bm/1989-0204-0-71.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/A_1989-0204-0-71",
    culture: "",
    country: "India",
    region: "Orissa: Bhubaneswar",
    objectDate: "1980s",
    medium: "silk",
    classification: "",
    department: "Asia",
    creditLine: "Purchased from: Martand Singh",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 5,
    objectID: "2018,2036.3",
    accession: "2018,2036.3",
    title: "Cloth",
    objectName: "cloth",
    imageFile: "bm/2018-2036-3.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2018-2036-3",
    culture: "Yoruba",
    country: "Nigeria",
    region: "",
    objectDate: "",
    medium: "Warp stripes in beige sanyan (wild silk) and white cotton.",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 6,
    objectID: "2018,2036.4",
    accession: "2018,2036.4",
    title: "Cloth",
    objectName: "cloth; garment",
    imageFile: "bm/2018-2036-4.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2018-2036-4",
    culture: "Yoruba",
    country: "Nigeria",
    region: "",
    objectDate: "19thC(late)-20thC(early) (circa)",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated through: Antony Griffiths (Cultural Gifts Scheme)",
    dimensions: "Length: 180 centimetres; Width: 133 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 7,
    objectID: "2018,2036.8",
    accession: "2018,2036.8",
    title: "Cloth",
    objectName: "cloth; garment",
    imageFile: "bm/2018-2036-8.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2018-2036-8",
    culture: "Yoruba",
    country: "Nigeria",
    region: "",
    objectDate: "20thC(early) (circa)",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated through: Antony Griffiths (Cultural Gifts Scheme)",
    dimensions: "Length: 209 centimetres; Width: 148 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 8,
    objectID: "2018,2036.9",
    accession: "2018,2036.9",
    title: "Cloth",
    objectName: "cloth; garment",
    imageFile: "bm/2018-2036-9.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2018-2036-9",
    culture: "Yoruba",
    country: "Nigeria",
    region: "Ondo State (?)",
    objectDate: "20thC(early) (circa)",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated through: Antony Griffiths (Cultural Gifts Scheme)",
    dimensions: "Length: 198 centimetres; Width: 119 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 9,
    objectID: "2018,2036.6.a",
    accession: "2018,2036.6.a",
    title: "Cloth",
    objectName: "cloth; garment",
    imageFile: "bm/2018-2036-6-a.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2018-2036-6-a",
    culture: "Yoruba",
    country: "Nigeria",
    region: "",
    objectDate: "20thC(early) (circa)",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated through: Antony Griffiths (Cultural Gifts Scheme)",
    dimensions: "Length: 191 centimetres; Width: 127 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 10,
    objectID: "2018,2036.2",
    accession: "2018,2036.2",
    title: "Cloth",
    objectName: "cloth; garment",
    imageFile: "bm/2018-2036-2.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2018-2036-2",
    culture: "Yoruba",
    country: "Nigeria",
    region: "",
    objectDate: "19thC (circa)",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated through: Antony Griffiths (Cultural Gifts Scheme)",
    dimensions: "Length: 200 centimetres; Width: 140 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 11,
    objectID: "2018,2036.5",
    accession: "2018,2036.5",
    title: "Cloth",
    objectName: "cloth; garment",
    imageFile: "bm/2018-2036-5.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2018-2036-5",
    culture: "Yoruba",
    country: "Nigeria",
    region: "",
    objectDate: "19thC(late)-20thC(early) (circa)",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated through: Antony Griffiths (Cultural Gifts Scheme)",
    dimensions: "Length: 190 centimetres; Width: 140 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 12,
    objectID: "2018,2036.55",
    accession: "2018,2036.55",
    title: "Cloth",
    objectName: "cloth",
    imageFile: "bm/2018-2036-55.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2018-2036-55",
    culture: "Yoruba",
    country: "Nigeria",
    region: "",
    objectDate: "1920-1940 (circa)",
    medium: "cotton; silk; rayon (?). The weft float motifs are in industrial cotton dyed to imitate the effect of sanyan wild silk.",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated through: Antony Griffiths (Cultural Gifts Scheme)",
    dimensions: "Length: 178 centimetres; Width: 124 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 13,
    objectID: "Af1843,0311.22",
    accession: "Af1843,0311.22",
    title: "Tobe",
    objectName: "tobe; gown; tunic",
    imageFile: "bm/Af1843-0311-22.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_Af1843-0311-22",
    culture: "Nupe",
    country: "Nigeria",
    region: "Kwara State: Eggan",
    objectDate: "1841 (circa)",
    medium: "cotton",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated by: Colonial Office",
    dimensions: "Length: 125 centimetres; Width: 255 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 14,
    objectID: "Af1943,12.1",
    accession: "Af1943,12.1",
    title: "Gown",
    objectName: "gown",
    imageFile: "bm/Af1943-12-1.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_Af1943-12-1",
    culture: "",
    country: "Nigeria",
    region: "Kano State",
    objectDate: "1909 (or shortly before)",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "From: Miss Rosa K Gibbs",
    dimensions: "Length: 143 centimetres; Width: 266 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 15,
    objectID: "2008,2025.21",
    accession: "2008,2025.21",
    title: "Gown",
    objectName: "gown; tobe",
    imageFile: "bm/2008-2025-21.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2008-2025-21",
    culture: "Hausa",
    country: "Nigeria",
    region: "Kaduna State: Zaria",
    objectDate: "1971",
    medium: "cotton; silk (wild)",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Purchased from: David Heathcote",
    dimensions: "Length: 141 centimetres; Width: 238 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 16,
    objectID: "2018,2036.6.b",
    accession: "2018,2036.6.b",
    title: "Head-tie",
    objectName: "head-tie",
    imageFile: "bm/2018-2036-6-b.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2018-2036-6-b",
    culture: "Yoruba",
    country: "Nigeria",
    region: "",
    objectDate: "20thC(early) (circa)",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated through: Antony Griffiths (Cultural Gifts Scheme)",
    dimensions: "Length: 230 centimetres; Width: 48 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 17,
    objectID: "2021,2022.2.a-b",
    accession: "2021,2022.2.a-b",
    title: "Skirt and Headscarf",
    objectName: "skirt; headscarf",
    imageFile: "bm/2021-2022-2-a-b.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2021-2022-2-a-b",
    culture: "Dafing",
    country: "Burkina Faso",
    region: "Ba",
    objectDate: "2020 (Aug-Oct)",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated by: Dr Laurence Douny",
    dimensions: "Skirt: Length 176 cm (max), Width 105 cm; Headscarf: Length 177 cm, Width 48 cm",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 18,
    objectID: "2021,2022.1.a-b",
    accession: "2021,2022.1.a-b",
    title: "Skirt and Headscarf",
    objectName: "skirt; headscarf",
    imageFile: "bm/2021-2022-1-a-b.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2021-2022-1-a-b",
    culture: "Dafing",
    country: "Burkina Faso",
    region: "Ba",
    objectDate: "2020 (July-Sept)",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated by: Dr Laurence Douny",
    dimensions: "Skirt: Length 180 cm, Width 123 cm (max); Headscarf: Length 181 cm, Width 61 cm",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 19,
    objectID: "2010,2013.8",
    accession: "2010,2013.8",
    title: "Hip-wrapper",
    objectName: "hip-wrapper",
    imageFile: "bm/2010-2013-8.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2010-2013-8",
    culture: "",
    country: "Burkina Faso",
    region: "Safane town",
    objectDate: "2006",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Funded by: Antony Griffiths",
    dimensions: "Length: 92.50 centimetres; Width: 154 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 20,
    objectID: "2010,2013.9",
    accession: "2010,2013.9",
    title: "Hip-wrapper",
    objectName: "hip-wrapper",
    imageFile: "bm/2010-2013-9.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2010-2013-9",
    culture: "",
    country: "Burkina Faso",
    region: "Safane town",
    objectDate: "2006",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Funded by: Antony Griffiths",
    dimensions: "Length: 95 centimetres; Width: 158 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 21,
    objectID: "2010,2013.4",
    accession: "2010,2013.4",
    title: "Hip-wrapper",
    objectName: "hip-wrapper",
    imageFile: "bm/2010-2013-4.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2010-2013-4",
    culture: "",
    country: "Burkina Faso",
    region: "Safane town",
    objectDate: "2006",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Funded by: Antony Griffiths",
    dimensions: "Length: 101 centimetres; Width: 155 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 22,
    objectID: "2010,2013.5",
    accession: "2010,2013.5",
    title: "Hip-wrapper",
    objectName: "hip-wrapper",
    imageFile: "bm/2010-2013-5.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2010-2013-5",
    culture: "",
    country: "Burkina Faso",
    region: "Safane town",
    objectDate: "2006",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Funded by: Antony Griffiths",
    dimensions: "Length: 93 centimetres; Width: 153 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 23,
    objectID: "As1980,Q.259",
    accession: "As1980,Q.259",
    title: "Robe",
    objectName: "robe; religious/ritual equipment",
    imageFile: "bm/As1980-Q-259.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/A_As1980-Q-259",
    culture: "Buddhist",
    country: "China",
    region: "Tibet (?)",
    objectDate: "19thC (? late?)",
    medium: "silk",
    classification: "",
    department: "Asia",
    creditLine: "",
    dimensions: "Length: 368 centimetres; Width: 100.50 centimetres",
    fibreBucket: "Tussah"
  },
  {
    id: 24,
    objectID: "2021,2022.6",
    accession: "2021,2022.6",
    title: "Sample",
    objectName: "sample",
    imageFile: "bm/2021-2022-6.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2021-2022-6",
    culture: "",
    country: "Côte d'Ivoire",
    region: "",
    objectDate: "2020",
    medium: "silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated by: Dr Laurence Douny",
    dimensions: "Length: 16.50 centimetres; Width: 14.50 centimetres; Depth: 1 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 25,
    objectID: "2021,2022.5",
    accession: "2021,2022.5",
    title: "Sample",
    objectName: "sample",
    imageFile: "bm/2021-2022-5.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2021-2022-5",
    culture: "",
    country: "Burkina Faso",
    region: "",
    objectDate: "2020",
    medium: "silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated by: Dr Laurence Douny",
    dimensions: "Length: 24 centimetres; Width: 3 centimetres; Depth: 3 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 26,
    objectID: "2021,2022.4",
    accession: "2021,2022.4",
    title: "Sample",
    objectName: "sample",
    imageFile: "bm/2021-2022-4.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_2021-2022-4",
    culture: "",
    country: "Côte d'Ivoire",
    region: "",
    objectDate: "2020",
    medium: "silkworm cocoon",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Donated by: Dr Laurence Douny",
    dimensions: "Length: 17 centimetres; Width: 16 centimetres; Depth: 8 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 27,
    objectID: "Af2006,23.17",
    accession: "Af2006,23.17",
    title: "Skirt",
    objectName: "skirt",
    imageFile: "bm/Af2006-23-17.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_Af2006-23-17",
    culture: "Dafing",
    country: "Mali",
    region: "Jalasago",
    objectDate: "2006",
    medium: "cotton; silk ((?))",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Purchased from: Kolado Cissé",
    dimensions: "Length: 152.50 centimetres; Width: 102 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 28,
    objectID: "Af2006,23.19",
    accession: "Af2006,23.19",
    title: "Skirt",
    objectName: "skirt",
    imageFile: "bm/Af2006-23-19.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_Af2006-23-19",
    culture: "Dafing",
    country: "Mali",
    region: "Jalasago",
    objectDate: "2006",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Purchased from: Kolado Cissé",
    dimensions: "Length: 140.50 centimetres; Width: 93.50 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 29,
    objectID: "Af2006,23.16",
    accession: "Af2006,23.16",
    title: "Skirt",
    objectName: "skirt",
    imageFile: "bm/Af2006-23-16.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_Af2006-23-16",
    culture: "Dafing",
    country: "Mali",
    region: "Jalasago",
    objectDate: "2006",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Purchased from: Kolado Cissé",
    dimensions: "Length: 155 centimetres; Width: 102.50 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  },
  {
    id: 30,
    objectID: "Af2006,23.18",
    accession: "Af2006,23.18",
    title: "Skirt",
    objectName: "skirt",
    imageFile: "bm/Af2006-23-18.png",
    sourceUrl: "https://www.britishmuseum.org/collection/object/E_Af2006-23-18",
    culture: "Dafing",
    country: "Mali",
    region: "Jalasago",
    objectDate: "2006",
    medium: "cotton; silk",
    classification: "",
    department: "Africa, Oceania and the Americas",
    creditLine: "Purchased from: Kolado Cissé",
    dimensions: "Length: 164 centimetres; Width: 94 centimetres",
    fibreBucket: "Wild silk (West Africa)"
  }
];
