/* ============================================================
   Indian Museum, Kolkata — wild silk objects
   Source: museumsofindia.gov.in (Ministry of Culture, Govt. of India)
   Every field below is VERBATIM from the source record.
   Do not paraphrase, normalise, or expand abbreviations.
   Fields left blank are pending entry from museum record screenshots.

   Field mapping (museum field → schema key):
     Title              → title
     Accession Number   → accession
     Object Type        → objectType
     Main Material      → mainMaterial
     Component Material II → componentMaterialII (only on some records)
     Country            → country
     Origin Place       → placeOfOrigin
     Find Place         → findPlace        (only on some records, e.g. tools/objects)
     Artist's Nationality→ artistNationality (only on some records)
     School             → school
     Period/Year of Work→ date
     Inscription        → inscription      (only on some records)
     Tribe              → tribe            (only on some records)
     Dimensions         → dimensions
     Brief Description  → briefDescription
   ============================================================ */

const imItems = [
  {
    id: 1,
    urlSlug: "im_kol-R-1898-S-1480-21992",
    accession: "R.1898/S.1480",
    title: "Textile",
    imageFile: "im/textile1.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1898-S-1480-21992",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Sibsagar, Assam",
    placeState: "Assam",
    school: "Tasar silk.",
    date: "C. 19th Century AD",
    dimensions: "L. 113 cm X B. 48 cm",
    briefDescription: "Sample piece of off white tasar silk cloth.",
    fibreBucket: "Tasar"
  },
  {
    id: 2,
    urlSlug: "im_kol-R-1949-S-688-19383",
    accession: "R.1949/S.688",
    title: "Textile",
    imageFile: "im/textile2.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1949-S-688-19383",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Maldah, Bengal",
    placeState: "West Bengal",
    school: "Tasar silk.",
    date: "C. 19th Century AD",
    dimensions: "L. 53 cm X B. 6.4 cm",
    briefDescription: "Sample piece of red colour tasar silk with floral border in golden silk thread.",
    fibreBucket: "Tasar"
  },
  {
    id: 3,
    urlSlug: "im_kol-R-1872-S-739-18623",
    accession: "R.1872/S.739",
    title: "Textile",
    imageFile: "im/textile3.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1872-S-739-18623",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Purulia, Manbhoom dist, West Bengal",
    placeState: "West Bengal",
    school: "Textile",
    date: "C. 19th Century AD",
    dimensions: "L. 95 cm X B. 47 cm",
    briefDescription: "Sample piece of tasar silk in beige colour.",
    fibreBucket: "Tasar"
  },
  {
    id: 4,
    urlSlug: "im_kol-R-1943-S-690-19449",
    accession: "R.1943/S.690",
    title: "Textile",
    imageFile: "im/textile4.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1943-S-690-19449",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Maldah, Bengal",
    placeState: "West Bengal",
    school: "Tasar",
    date: "C. 19th Century AD",
    dimensions: "L. 38 cm X B. 4 cm",
    briefDescription: "Sample piece of tasar silk with wavy or beki design.",
    fibreBucket: "Tasar"
  },
  {
    id: 5,
    urlSlug: "im_kol-R-1950-S-682-19382",
    accession: "R.1950/S.682",
    title: "Textile",
    imageFile: "im/textile5.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1950-S-682-19382",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Maldah, Bengal",
    placeState: "West Bengal",
    school: "Silk",
    date: "C. 19th Century AD",
    dimensions: "L. 105.2 cm X B. 6.4 cm",
    briefDescription: "Green colour sample piece of tasar silk with red border.",
    fibreBucket: "Tasar"
  },
  {
    id: 6,
    urlSlug: "im_kol-R-1936-S-683-19419",
    accession: "R.1936/S.683",
    title: "Textile",
    imageFile: "im/textile6.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1936-S-683-19419",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Maldah, Bengal",
    placeState: "West Bengal",
    school: "Tasar",
    date: "C. 19th Century AD",
    dimensions: "L. 76 cm X B. 6 cm",
    briefDescription: "Sample piece of green, red and yellow coloured tasar silk fabric.",
    fibreBucket: "Tasar"
  },
  {
    id: 7,
    urlSlug: "im_kol-R-1947-S-686-19452",
    accession: "R.1947/S.686",
    title: "Textile",
    imageFile: "im/textile7.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1947-S-686-19452",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Maldah, Bengal",
    placeState: "West Bengal",
    school: "Tasar",
    date: "C. 19th Century AD",
    dimensions: "L. 38 cm X B. 9 cm",
    briefDescription: "Sample piece of red, black and beige colored tasar silk with floral butas.",
    fibreBucket: "Tasar"
  },
  {
    id: 8,
    urlSlug: "im_kol-R-1941-S-684-19373",
    accession: "R.1941/S.684",
    title: "Textile",
    imageFile: "im/textile8.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1941-S-684-19373",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Maldah, Bengal",
    placeState: "West Bengal",
    school: "Silk",
    date: "C.19th Century AD",
    dimensions: "L. 19.7 cm X B. 7.6 cm",
    briefDescription: "Sample piece of multicoloured tasar silk with 'Beki' design shows green, red and yellow colour.",
    fibreBucket: "Tasar"
  },
  {
    id: 9,
    urlSlug: "im_kol-R-1942-S-687-19444",
    accession: "R.1942/S.687",
    title: "Textile",
    imageFile: "im/textile9.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1942-S-687-19444",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Maldah, Bengal",
    placeState: "West Bengal",
    school: "Tasar",
    date: "C. 19th Century AD",
    dimensions: "L. 38 cm X B. 8 cm",
    briefDescription: "Sample piece of tasar silk of red, white, yellow and black coloured shows wavy or beki design.",
    fibreBucket: "Tasar"
  },
  {
    id: 10,
    urlSlug: "im_kol-710-17497",
    accession: "710",
    title: "Tasar spindle",
    imageFile: "im/textile10.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-710-17497",
    objectType: "Domestic Appliances",
    mainMaterial: "Wood",
    country: "India",
    placeOfOrigin: "Ranchi, Jharkhand, India.",
    placeState: "Jharkhand",
    findPlace: "Ranchi, Jharkhand, India.",
    school: "",
    date: "19th Century",
    inscription: "NA",
    tribe: "Not Known.",
    dimensions: "Length- 37 cm, Breadth- 5.1 cm.",
    briefDescription: "Tasar spindle : Wooden spindle, working part is elliptical shaped with pointed end, three bars are present transversely and three bars horizontally attached in the middle part of the elliptical body, short handle is present, used for weaving 'tasar silk'.",
    fibreBucket: "Tasar"
  },
  {
    id: 11,
    urlSlug: "im_kol-R-1854-S-1190-21990",
    accession: "R.1854/S.1190",
    title: "Textile",
    imageFile: "im/textile11.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1854-S-1190-21990",
    objectType: "Textile",
    mainMaterial: "Tussar",
    country: "India",
    placeOfOrigin: "Kurdah, Orissa",
    placeState: "Odisha",
    school: "Tasar silk.",
    date: "19th Century CE",
    dimensions: "L. 113 cm X B. 53 cm",
    briefDescription: "Sample piece of tasar cloth.",
    fibreBucket: "Tasar"
  },
  {
    id: 12,
    urlSlug: "im_kol-R-1861-S-920-18795",
    accession: "R.1861/S.920",
    title: "Textile",
    imageFile: "im/textile12.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1861-S-920-18795",
    objectType: "Textile",
    mainMaterial: "Others",
    artistNationality: "Indian",
    country: "India",
    placeOfOrigin: "Bankura",
    placeState: "West Bengal",
    school: "Tasar silk.",
    date: "20th Century",
    dimensions: "L. 70.4 cm, B. 50.3 cm",
    briefDescription: "Sample of Tasar cloth.",
    fibreBucket: "Tasar"
  },
  {
    id: 13,
    urlSlug: "im_kol-R-1889-S-1668-21865",
    accession: "R.1889/S.1668",
    title: "Textile",
    imageFile: "im/textile13.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1889-S-1668-21865",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Balasore Dist.",
    placeState: "Odisha",
    school: "Tasar silk.",
    date: "C. 19th Century AD",
    dimensions: "L. 459 cm X B. 117 cm",
    briefDescription: "Red bordered tasar dhuti (Coarse tasar cloth).",
    fibreBucket: "Tasar"
  },
  {
    id: 14,
    urlSlug: "im_kol-R-1904-S-693-21991",
    accession: "R.1904/S.693",
    title: "Textile",
    imageFile: "im/textile14.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1904-S-693-21991",
    objectType: "Textile",
    mainMaterial: "Silk",
    componentMaterialII: "Cotton",
    country: "India",
    placeOfOrigin: "Patna dist, India",
    placeState: "Bihar",
    school: "Tasar silk.",
    date: "19th Century CE",
    dimensions: "L. 80 cm X B. 55.5 cm",
    briefDescription: "Coarse tassar and cotton checkered cloth.",
    fibreBucket: "Tasar"
  },
  {
    id: 15,
    urlSlug: "im_kol-R-1781-S-714-20426",
    accession: "R.1781/S.714",
    title: "Textile",
    imageFile: "im/textile15.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1781-S-714-20426",
    objectType: "Textile",
    mainMaterial: "Tussar",
    country: "India",
    placeOfOrigin: "Calcutta",
    placeState: "West Bengal",
    school: "Textile",
    date: "C. 19th Century AD",
    dimensions: "L. 64 cm, B. 109 cm",
    briefDescription: "Sample piece of tussar fabric.",
    fibreBucket: "Tasar"
  },
  {
    id: 16,
    urlSlug: "im_kol-R-1886-S-1349-21993",
    accession: "R.1886/S.1349",
    title: "Textile",
    imageFile: "im/textile16.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1886-S-1349-21993",
    objectType: "Textile",
    mainMaterial: "Tussar",
    country: "India",
    placeOfOrigin: "Patna Dist., Bihar",
    placeState: "Bihar",
    school: "Tussar",
    date: "19th Century CE",
    dimensions: "L. 90 cm X B. 34 cm",
    briefDescription: "Sample piece of purple tassar cloth.",
    fibreBucket: "Tasar"
  },
  {
    id: 17,
    urlSlug: "im_kol-R-1871-S-1783-20418",
    accession: "R.1871/S.1783",
    title: "Textile",
    imageFile: "im/textile17.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1871-S-1783-20418",
    objectType: "Textile",
    mainMaterial: "Cloth",
    country: "India",
    placeOfOrigin: "Bankura Dist.",
    placeState: "West Bengal",
    school: "Textile",
    date: "C. 19th Century AD",
    dimensions: "L. 457 cm, B. 64.3 cm",
    briefDescription: "Tussar cloth plain.",
    fibreBucket: "Tasar"
  },
  {
    id: 18,
    urlSlug: "im_kol-R-958-S-1458-21973",
    accession: "R.958/S.1458",
    title: "Textile",
    imageFile: "im/textile18.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-958-S-1458-21973",
    objectType: "Textile",
    mainMaterial: "Tussar",
    country: "India",
    placeOfOrigin: "Midnapur jail, West Bengal",
    placeState: "West Bengal",
    school: "Tasar",
    date: "19th Century CE",
    dimensions: "L. 100 cm X B. 30 cm",
    briefDescription: "Sample piece of 'amiantine cartridge' cloth, made from refuse tasar.",
    fibreBucket: "Tasar"
  },
  {
    id: 19,
    urlSlug: "im_kol-R-1862-S-915-19355",
    accession: "R.1862/S.915",
    title: "Textile",
    imageFile: "im/textile19.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-1862-S-915-19355",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Bihar, Sub-division of Patna",
    placeState: "Bihar",
    school: "Sample piece of yellow tussar",
    date: "C. 19th Century AD",
    dimensions: "L. 48 cm X B. 47 cm",
    briefDescription: "Sample piece of tasar.",
    fibreBucket: "Tasar"
  },
  {
    id: 20,
    urlSlug: "im_kol-R-959-S-768-19220",
    accession: "R.959/S.768",
    title: "Textile",
    imageFile: "im/textile20.png",
    sourceUrl: "https://museumsofindia.gov.in/repository/record/im_kol-R-959-S-768-19220",
    objectType: "Textile",
    mainMaterial: "Silk",
    country: "India",
    placeOfOrigin: "Beerhoom (Birbhum dist.), West Bengal",
    placeState: "West Bengal",
    school: "Silk cloth",
    date: "C. 19th Century AD",
    dimensions: "L. 284 cm X B. 75 cm",
    briefDescription: "Specimen of matka or coarse silk fabric in beige color shows three fine horizontal stripes in purple colour at the edge.",
    fibreBucket: "Tasar"
  }
];

const imFilterDefinitions = {
  fibreBucket: ["Tasar", "Tussore", "Eri", "Muga"],
  placeState: [],
  objectType: []
};
