// Whitworth Art Gallery (University of Manchester) — wild silk records
// Verbatim from whitworthcollections.manchester.ac.uk

const whItems = [
  {
    id: 1,
    objectID: "T.1985.105",
    accession: "T.1985.105",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/tussur-shared.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/e3b3d67d-04b0-3f3a-8e17-d1d95e9fc0c8/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk with narrow borders of small boteh woven in purple silk. One loom end is preserved with a band of bare warp ends flanked by pairs of bands of purple silk, the other end is cut. The cloth includes some dark, streaky patches of yarn near the selvedges.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 2,
    objectID: "T.1985.106",
    accession: "T.1985.106",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/tussur-shared.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/9a19976c-05bd-3058-8119-50fbbc383fb4/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk with narrow borders of small boteh woven in purple silk. One loom end preserved with a band of bare warp ends flanked by a series of bands of purple silk.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 3,
    objectID: "T.1985.107",
    accession: "T.1985.107",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/tussur-shared.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/c6f9816f-00c0-3999-8c77-660ee3c47ae8/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk with narrow borders of small boteh woven in purple silk. One loom end preserved with a band of bare warp ends flanked by pairs of bands of purple silk, the other end is cut. The cloth includes some dark, streaky patches of yarn near the selvedges. There is some water staining at one end.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 4,
    objectID: "T.1985.109",
    accession: "T.1985.109",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/tussur-shared.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/120e4fec-6e45-34a8-9335-83ea3d358b2c/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 5,
    objectID: "T.1985.110",
    accession: "T.1985.110",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/T-1985-110.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/71779912-f4b0-3014-95f2-a21f89311957/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk with narrow borders of small boteh woven in purple silk edged with purple pin stripes on both sides. Both loom ends are preserved, each with a band of bare warp ends flanked by a series of bands of purple silk.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  },
  {
    id: 6,
    objectID: "T.1985.129",
    accession: "T.1985.129",
    title: "Length of tussur silk",
    objectName: "cloth",
    imageFile: "wh/T-1985-129.png",
    sourceUrl: "https://whitworthcollections.manchester.ac.uk/collections/item/19b6887b-38eb-3a16-9734-9198f6451e5f/",
    culture: "Indian, maker",
    country: "India",
    region: "Giridi, Bengal",
    objectDate: "1880-1885",
    medium: "Length of undyed tusser silk with narrow borders of small boteh woven in purple silk. One loom end preserved with a band of bare warp ends flanked by pairs of bands of purple silk, the other end is cut. The cloth includes some dark, streaky patches of yarn near the selvedges. There is an L-shaped tear in the cloth.",
    classification: "textiles (woven)",
    department: "Art and Material Culture of the Islamic World",
    creditLine: "",
    dimensions: "",
    fibreBucket: "Tasar"
  }
];
