/* ============================================================
   Forbes Watson 1866 — wild silk swatches (6 of 662)
   Source: tmoi.org.uk, Harris Museum & Art Gallery, Preston.
   Every field below is VERBATIM from the source product page.
   Do not paraphrase, normalise units, or expand abbreviations.
   ============================================================ */

const fwItems = [
  {
    id: 1,
    sampleNo: "289",
    volume: 8,
    volumeTitle: "Volume VIII: Muslins, Calicoes and other Piece Goods",
    title: "Muslins.",
    imageFile: "watson/1993_68_8_289.jpg",
    accession: "1993.68.8.289",
    sourceUrl: "http://tmoi.org.uk/index.php?option=com_virtuemart&page=shop.product_details&flypage=flypage-ask.tpl&product_id=249",
    extraInfo: "Muslins. Very light muslin, \"Santipore Dhootee.\" Colored figured borders, with tussah silk worked therein.",
    material: "Cotton and silk",
    pattern: "Plain with Border",
    technique: "Woven",
    mainColours: "White and Pink",
    use: "Fabrics general",
    type: "None",
    length: "5 Yards 32 Inches",
    width: "1 Yard 9 Inches",
    weight: "5",
    price: "5s. 6d.",
    placeModern: "Shantipur, West Bengal, India",
    placeFw: "Santipore; Calcutta",
    region: "West Bengal",
    fibre: "Tussah (in border)",
    dyeBucket: "Dyed",
    fibreBucket: "Tussah"
  },
  {
    id: 2,
    sampleNo: "556",
    volume: 14,
    volumeTitle: "Volume XIV: Silk Piece Goods",
    title: "Tussur silk.",
    imageFile: "watson/1993_68_14_556.jpg",
    accession: "1993.68.14.556",
    sourceUrl: "http://tmoi.org.uk/index.php?option=com_virtuemart&page=shop.product_details&flypage=flypage-ask.tpl&product_id=517",
    extraInfo: "Tussur silk. Tussur silk, plain.",
    material: "Silk",
    pattern: "Plain",
    technique: "None",
    mainColours: "Beige",
    use: "Fabrics general",
    type: "None",
    length: "10 yards 18 inches",
    width: "1 yard 1 inch",
    weight: "1 lb. 15",
    price: "15s. 10",
    placeModern: "Warangal, Andhra Pradesh, India",
    placeFw: "Warungul, Hyderabad; Deccan",
    region: "Andhra Pradesh",
    fibre: "Tussur",
    dyeBucket: "Undyed",
    fibreBucket: "Tussur"
  },
  {
    id: 3,
    sampleNo: "557",
    volume: 14,
    volumeTitle: "Volume XIV: Silk Piece Goods",
    title: "Tussur silk.",
    imageFile: "watson/1993_68_14_557.jpg",
    accession: "1993.68.14.557",
    sourceUrl: "http://tmoi.org.uk/index.php?option=com_virtuemart&page=shop.product_details&flypage=flypage-ask.tpl&product_id=518",
    extraInfo: "Tussur silk. Tussur silk (twilled). Dyed.",
    material: "Silk",
    pattern: "Plain",
    technique: "None",
    mainColours: "Grey",
    use: "Fabrics general",
    type: "None",
    length: "11 yards",
    width: "26 inches",
    weight: "1 lb. 7",
    price: "13s.",
    placeModern: "Bhagalpur, Bihar, India",
    placeFw: "Bhagulpore; Bengal",
    region: "Bihar",
    fibre: "Tussur",
    dyeBucket: "Dyed",
    fibreBucket: "Tussur"
  },
  {
    id: 4,
    sampleNo: "558",
    volume: 14,
    volumeTitle: "Volume XIV: Silk Piece Goods",
    title: "Tussur silk.",
    imageFile: "watson/1993_68_14_558.jpg",
    accession: "1993.68.14.558",
    sourceUrl: "http://tmoi.org.uk/index.php?option=com_virtuemart&page=shop.product_details&flypage=flypage-ask.tpl&product_id=519",
    extraInfo: "Tussur silk. Tussur silk, large check. Dyed.",
    material: "Silk",
    pattern: "Checks",
    technique: "Woven",
    mainColours: "Red, pink, white",
    use: "Fabrics general",
    type: "None",
    length: "9 yards 18 inches",
    width: "25",
    weight: "1 lb. 4 oz.",
    price: "13s.",
    placeModern: "Bhagalpur, Bihar, India",
    placeFw: "Bhagulpore; Bengal",
    region: "Bihar",
    fibre: "Tussur",
    dyeBucket: "Dyed",
    fibreBucket: "Tussur"
  },
  {
    id: 5,
    sampleNo: "559",
    volume: 14,
    volumeTitle: "Volume XIV: Silk Piece Goods",
    title: "Eria silk.",
    imageFile: "watson/1993_68_14_559.jpg",
    accession: "1993.68.14.559",
    sourceUrl: "http://tmoi.org.uk/index.php?option=com_virtuemart&page=shop.product_details&flypage=flypage-ask.tpl&product_id=520",
    extraInfo: "Eria silk. Eria silk piece, named 'Dooklee'; coarse.",
    material: "Silk",
    pattern: "Plain",
    technique: "None",
    mainColours: "Grey",
    use: "Fabrics general",
    type: "None",
    length: "4 yards",
    width: "34 inches",
    weight: "1 lb. 6 oz.",
    price: "4s.",
    placeModern: "Cachar, Assam, India",
    placeFw: "Cachar; Bengal",
    region: "Assam",
    fibre: "Eria",
    dyeBucket: "Undyed",
    fibreBucket: "Eria"
  },
  {
    id: 6,
    sampleNo: "560",
    volume: 14,
    volumeTitle: "Volume XIV: Silk Piece Goods",
    title: "Eria silk.",
    imageFile: "watson/1993_68_14_560-2.jpg",
    accession: "1993.68.14.560",
    sourceUrl: "http://tmoi.org.uk/index.php?option=com_virtuemart&page=shop.product_details&flypage=flypage-ask.tpl&product_id=521",
    extraInfo: "Eria silk. Eria (wild) silk. Piece named 'Endi' cloth. Used for garments by men and women.",
    material: "Silk",
    pattern: "Plain with border",
    technique: "Woven",
    mainColours: "Red, yellow",
    use: "Clothing",
    type: "Garment",
    length: "3 yards 2 inches",
    width: "1 yard 4 inches",
    weight: "1 lb. 4 oz.",
    price: "0",
    placeModern: "Darjeeling, West Bengal, India",
    placeFw: "Darjeeling",
    region: "West Bengal",
    fibre: "Eria",
    dyeBucket: "Dyed",
    fibreBucket: "Eria"
  }
];

const fwFilterDefinitions = {
  fibreBucket: ["Tussur", "Tussah", "Eria"],
  region: ["West Bengal", "Bihar", "Assam", "Andhra Pradesh"],
  volume: [8, 14],
  dyeBucket: ["Dyed", "Undyed"]
};
