// Pitt Rivers Museum (Oxford) — wild silk records
// Verbatim from prm.ox.ac.uk/collections-online

const prItems = [
  {
    id: 1,
    objectID: "1955.11.57",
    accession: "1955.11.57",
    title: "Bag",
    objectName: "bag",
    imageFile: "pr/1955-11-57.png",
    sourceUrl: "https://www.prm.ox.ac.uk/collections-online#/item/prm-object-125256",
    culture: "Khamti (uncertain)",
    country: "India",
    region: "Assam / Nagaland / Arunachal Pradesh / Mizoram / Meghalaya (uncertain)",
    objectDate: "Circa 1937",
    medium: "Cotton Yarn Plant; Pigment; Silk Yarn Animal (muga)",
    classification: "Woven; Embroidered; Dyed",
    department: "",
    creditLine: "Donated 1955 by Robert Niel Reid",
    dimensions: "Length x Width: max 650 x 275 mm",
    fibreBucket: "Muga"
  },
  {
    id: 2,
    objectID: "1949.1.6",
    accession: "1949.1.6",
    title: "Sash",
    objectName: "sash",
    imageFile: "pr/1949-1-6.png",
    sourceUrl: "https://www.prm.ox.ac.uk/collections-online#/item/prm-object-20563",
    culture: "",
    country: "Mexico",
    region: "South Oaxaca, Sierra de Juarez, San Francisco Cajonas",
    objectDate: "Before 1949",
    medium: "Silk Textile Animal (wild cocoon silk)",
    classification: "Woven",
    department: "",
    creditLine: "Donated 1949 by Elsie Colsell McDougall",
    dimensions: "Length: max 840 mm; Width: max 560 mm",
    fibreBucket: "Wild silk (Mexico)"
  },
  {
    id: 3,
    objectID: "1949.1.7",
    accession: "1949.1.7",
    title: "Belt",
    objectName: "belt",
    imageFile: "pr/1949-1-7.png",
    sourceUrl: "https://www.prm.ox.ac.uk/collections-online#/item/prm-object-20700",
    culture: "Zapotec — Zapotecos de la Sierra Norte",
    country: "Mexico",
    region: "South Oaxaca, Sierra de Juarez, San Francisco Cajonas",
    objectDate: "Before 1949",
    medium: "Silk Textile Animal (spun wild cocoon silk); Pigment",
    classification: "Woven; Dyed",
    department: "",
    creditLine: "Donated 1949 by Elsie Colsell McDougall",
    dimensions: "Width: 45 mm; Length: 1005 mm without fringe",
    fibreBucket: "Wild silk (Mexico)"
  },
  {
    id: 4,
    objectID: "1944.5.2B",
    accession: "1944.5.2B",
    title: "Embroidery",
    objectName: "wild silk textile embroidered with red and green floral designs",
    imageFile: "pr/1944-5-2B.png",
    sourceUrl: "https://www.prm.ox.ac.uk/collections-online#/item/prm-object-46371",
    culture: "",
    country: "China",
    region: "Uighur Autonomous Region of Sinkiang (Xinjiang Province), Kashgar (Kashi)",
    objectDate: "Before 15/10/1930",
    medium: "Silk Textile Animal; Silk Yarn Animal",
    classification: "Embroidered; Woven",
    department: "",
    creditLine: "Purchased 1944 — The Estate of Marc Aurel Stein / Helen Mary Allen",
    dimensions: "Width: 380 mm; Length: 660 mm",
    fibreBucket: "Wild silk (other)"
  }
];
